Fix VS2010 and "error C2065: uint32_t: undeclared identifier" (GH #608) We could fix aria.cpp by using word32. However, NaCl gear uses int64_t and we don't have a typedef setup for it. So we will need <cstdint> later for NaCl